api_platform:
    title: Hello API Platform
    version: 1.0.0
    http_cache:
        invalidation:
            enabled: true
    defaults:
        pagination_items_per_page: 10
        stateless: true
        cache_headers:
            vary: ['Authorization', 'Accept-Language']
