controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin:
    resource: '../src/Controller/AdminController/'
    type: attribute
    prefix: '/admin'

api_login_check:
    path: /api/login_check